### ISSUE TITLE
/station

### ISSUE THREAD

**Issue by eisc** [eisc/fancy_LVB_Telegram_Bot#13]
"Nutzer gibt /station und einen Haltestellennamen ein und erhält den Standort der entsprechenden Haltestelle. Fehlt der Haltestellenname gibt es eine entsprechende Fehlermeldung."

**Comment by eisc** [comment]
hängt von #10 ab (die Haltestellennamen)

**Comment by NucsuM** [comment]
Idee: Gibt es mehrere Haltestellen mit dem Namen (bspw. 'Münz'), könnte dem Nutzer per Inline-Keyboard eine Auswahlliste angezeigt werden. Er kann dann auf seine gewünschte draufklicken.

**Comment by eisc** [comment]
closed with commit 59b18bc22667b19d784ab4ce53f1165c7b5a8b98
