### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by NucsuM** [eisc/fancy_LVB_Telegram_Bot#18]
Es wäre schön, wenn wir eine Möglichkeit finden könnten den Bot irgendwo zu deployen. Zwei Hinweise/Wünsche habe ich dazu aber noch.

1) Es wäre schön, wenn wir ohne viel Adminwissen/rechte selbst den letzten Stand des Masters einfach bereitstellen könnten. 

2) @eisc und ich haben je eine config.js, in der der API-Token ist enthalten. Der muss ja während des Betriebes auch mit bei liegen. die config.js muss bei der Bereitstellung irgendwoher geholt werden und darf nicht auf Github liegen. So sieht die Config aus, natürlich mit korrekten token ;)

```js
var config = {}
config.TELEGRAM_TOKEN = '000000000:xxxxxxxxxxxxxxxxxxxxx'
module.exports = config;
```

**Comment by joergreichert** [comment]
https://medium.com/roomjs/telegram-bot-on-javascript-with-free-hosting-53ae01bce991 schlägt https://glitch.com/ vor. Den Code könnte man dort sogar direkt editieren, z.B. wie hier https://glitch.com/edit/#!/atg-bot?path=README.md:1:0

Alternativ, wie hier beschrieben, mit AWS Lambda: https://medium.freecodecamp.org/how-to-build-a-server-less-telegram-bot-227f842f4706

**Comment by eisc** [comment]
beides scheint eher nur für eine Testphase geeignet zu sein und nicht für einen ernsthafteren Betrieb. aber das reicht ja auch erstmal. :)

wenn ich mir so dir Wünsche von @NucsuM anschaue ist glitch ist für unsere Zwecke das Richtige, da kann man von Github direkt Code importieren und es gibt eine Möglichkeit den Token geheim zu hinterlegen.
