### ISSUE TITLE
Modularisierung

### ISSUE THREAD

**Issue by NucsuM** [eisc/fancy_LVB_Telegram_Bot#21]
Alles in einer index.js Datei zu halten wird mit steigender Komplexität immer unübersichtlicher.

Vorschlag:
index.js ->  alles importieren
gtfs.js -> Funktionen welche die GTFS-API abfragen
helper.js -> Hilfsfunktionen
lvb.js -> LVB api
bot.js -> Bot-io (bot.on, regex)

**Comment by eisc** [comment]
closed by 0974bc33f4bf7ad17a8e1ea2a75412e0ea64afed
