### ISSUE TITLE
Nur Daten aus Leipziger Gebiet verwenden

### ISSUE THREAD

**Issue by joergreichert** [eisc/fancy_LVB_Telegram_Bot#23]
Stops usw. nur aus Stadt Leipzig in Ergebnissen anzeigen, so dass die Suche nach Hauptbahnhof nur den in Leipzig anzeigt

**Comment by eisc** [comment]
vielleicht können wir am Anfang eine Abfrage nach dem Heimatort oder so machen. also wenn man in Halle wohnt, dann kann man das als Gebiet festlegen und dann wird bei der HBF Abfrage Halle Hbf gesucht.

**Comment by eisc** [comment]
ich denke erstmal haben wir da einen Workaround, oder?
